### ISSUE TITLE
Works on XinPro but not alternative frame mode

### ISSUE THREAD

**Issue by hillyu** [PetePriority/chicony-ir-toggle#6]
Thanks for your great work on Ir toggle. I was thrilled to find that I could enable my IR cam with this. However I noticed that with the current method, it will only turn on the ir led rather than "making it flash". Luckily I tried one of your method mentioned on Howdy github discussion and managed to enable alternateive frame mode on mine.
for detail and code see: https://github.com/hillyu/chicony-ir-toggle.git

**Comment by PetePriority** [comment]
Thanks! I'm glad I could help :) 
I've added your device and a link to your fork to the readme

**Comment by Jeder321** [comment]
The same problem also is on my T495 and this fork helped
